# =========================
# STAGE 1: BUILD FRONTEND
# =========================
ARG NODE_VERSION=22.14.0-alpine
FROM node:${NODE_VERSION} AS node_builder
WORKDIR /var/www
# . copy dependency trước
COPY package.json package-lock.json ./
RUN npm install --no-audit

# Copy configuration and source files
COPY vite.config.js ./
COPY resources/ resources/
COPY public/ public/

# Run the build command
RUN npm run build


# =========================
# STAGE 2: PHP (FINAL)
# =========================
FROM php:8.4-fpm-alpine
# Arguments defined in docker-compose.yml
ARG user
ARG uid

ENV ASUSER= \
    UID= \
    COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_MEMORY_LIMIT=-1 \
    ENABLE_XDEBUG=false \
    PHP_DATE_TIMEZONE=UTC \
    PHP_MEMORY_LIMIT=256M \
    PHP_MAX_INPUT_VARS=1000 \
    PHP_UPLOAD_MAX_FILESIZE=25M \
    PHP_POST_MAX_SIZE=25M \
    PHP_MAX_EXECUTION_TIME=30 \
    PHP_FPM_LISTEN=9000 \
    PHP_FPM_MAX_CHILDREN=10 \
    PHP_FPM_REQUEST_TERMINATE_TIMEOUT=60 \
    ENTRYPOINT=entrypoint.php.sh

# Setup working directory
WORKDIR /var/www/

RUN adduser -D -u 1337 hoadev \
    && addgroup hoadev www-data \
    # dockerize
    && DOCKERIZE_ARCH="$( [ "$(uname -m)" = "aarch64" ] && echo arm64 || echo amd64 )" \
    && curl -L "https://github.com/jwilder/dockerize/releases/download/v0.9.3/dockerize-linux-${DOCKERIZE_ARCH}-v0.9.3.tar.gz" | tar xz \
    && mv dockerize /usr/local/bin/dockerize \
    # deps
    && apk --no-cache add su-exec bash sed git openssh-client icu shadow procps \
        freetype libpng libjpeg-turbo libzip-dev ghostscript imagemagick \
        jpegoptim optipng pngquant gifsicle libldap \
        libpq less \
    # build-deps
    && cp "/usr/local/etc/php/php.ini-development" "/usr/local/etc/php/php.ini" \
    && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
        freetype-dev libpng-dev libjpeg-turbo-dev \
        icu-dev libedit-dev libxml2-dev \
        imagemagick-dev openldap-dev oniguruma-dev libwebp-dev \
        postgresql-dev \
        linux-headers \
    # php-ext
    && docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg \
    && export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    && docker-php-ext-install -j$(nproc) \
        bcmath \
        calendar \
        exif \
        gd \
        intl \
        ldap \
        mbstring \
        pcntl \
        pdo \
        pdo_mysql \
        pdo_pgsql \
        soap \
        xml \
        zip \
        sockets \
        mysqli \
        ftp \
    && pecl install redis \
    && pecl install xdebug \
    && pecl install pcov && docker-php-ext-enable pcov \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && docker-php-ext-enable redis \
    # composer
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && curl -sS https://getcomposer.org/installer | php -- --1 --install-dir=/usr/local/bin --filename=composer1 \
    # cleanup
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* /tmp/*

# Copy source code
COPY . .

# Copy ONLY the built React assets from the node_builder stage
COPY --from=node_builder /var/www/public/build ./public/build

CMD ["php-fpm"]
